# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Bg-img-with-overlay"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
    image_path: https://res.cloudinary.com/aggtrans/image/upload/f_auto,q_auto,dpr_auto/equipment/HeaderIMG-About-Us.jpg
    image_alt: Loader moving topsoil
  logo_image:
    image_path: https://res.cloudinary.com/aggtrans/image/upload/w_600,fl_progressive:semi/f_auto,q_auto/logos/    Aggtrans_over_40_year_logo_items_white_DELV.png
    image_alt: Aggtrans logo
    position_left: 50

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
