# /bookshop/components/aboutUs/aboutUs.bookshop.yml

# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "About Us Section"
  description: "Section for displaying information about the company with headings, texts, and images."
  icon: info
  tags: ['about', 'section', 'company', 'information']

# Defines the structure of this component, as well as the default values
blueprint:
  topper: 
    type: text
    label: "Topper"
    default: "Your Topper Text Here"
  mainHeading: 
    type: text
    label: "Main Heading"
    default: "About Our Company"
  mainIntro: 
    type: markdown
    label: "Main Introduction"
    default: "We have been serving for decades, ensuring quality and commitment in all our services."
  secondHeading: 
    type: text
    label: "Second Heading"
    default: "Our Mission"
  secondText: 
    type: markdown
    label: "Second Text"
    default: "To provide exceptional services and quality products."
  thirdHeading: 
    type: text
    label: "Third Heading"
    default: "Our Vision"
  thirdText: 
    type: markdown
    label: "Third Text"
    default: "To be a leader in the industry by setting high standards and inspiring others."
  firstImgSM: 
    type: image
    label: "First Image (Mobile)"
  firstImgLG: 
    type: image
    label: "First Image (Desktop)"
  firstImgAlt: 
    type: text
    label: "First Image Alt Text"
    default: "Team working together"
  secondImgSM: 
    type: image
    label: "Second Image (Mobile)"
  secondImgLG: 
    type: image
    label: "Second Image (Desktop)"
  secondImgAlt: 
    type: text
    label: "Second Image Alt Text"
    default: "Office environment"
  numberOfYears: 
    type: text
    label: "Number of Years"
    default: "25"
  servingDetails: 
    type: text
    label: "Serving Details"
    default: "Years of Excellence"
  styles: # Adding the styles section here
    color_group: "primary"
    custom_css: |
      #sbs-1067 {
        padding: var(--sectionPadding);
      }
      #sbs-1067 .cs-container {
        width: 100%;
        max-width: 34.375rem;
        margin: auto;
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: clamp(3rem, 6vw, 4rem);
      }
      #sbs-1067 .cs-content {
        text-align: left;
        width: 100%;
        max-width: 33.875rem;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
      }
      #sbs-1067 .cs-text {
        margin-bottom: 1rem;
      }
      #sbs-1067 .cs-text:last-of-type {
        margin-bottom: 2rem;
      }
      #sbs-1067 .cs-list {
        margin: 0 0 2rem 0;
        padding: 0;
        display: flex;
        align-items: flex-start;
        flex-direction: column;
        gap: 1.5rem;
      }
      #sbs-1067 .cs-li {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: flex-start;
        justify-content: flex-start;
        gap: 1.25rem;
      }
      #sbs-1067 .cs-h3 {
        font-size: clamp(1.25rem, 2.5vw, 1.5625rem);
        line-height: 1.2em;
        font-weight: 700;
        text-align: left;
        margin: 0 0 0.75rem 0;
        color: var(--headerColor);
      }
      #sbs-1067 .cs-li-text {
        font-size: clamp(0.875rem, 1.8vw, 1rem);
        line-height: 1.5em;
        text-align: left;
        margin: 0;
        color: var(--bodyTextColor);
      }
      #sbs-1067 .cs-image-group {
        font-size: min(2.235vw, 0.8em);
        width: 40.625em;
        height: 40.8125em;
        display: block;
        position: relative;
        z-index: 1;
      }
      #sbs-1067 .cs-picture {
        position: absolute;
      }
      #sbs-1067 .cs-picture img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        position: absolute;
        top: 0;
        left: 0;
      }
      #sbs-1067 .cs-box {
        width: 100%;
        max-width: 10.625rem;
        padding: 1.5rem;
        box-sizing: border-box;
        background-color: var(--primary);
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        position: absolute;
        z-index: 20;
        left: 6.375em;
        bottom: 4.9375em;
      }
      #sbs-1067 .cs-number {
        font-size: clamp(1.25rem, 4vw, 2.4375rem);
        text-align: center;
        line-height: 1.2em;
        font-weight: 700;
        width: 100%;
        margin: 0 0 clamp(0.25rem, 1vw, 0.5rem);
        color: var(--bodyTextColorWhite);
        display: block;
      }
      #sbs-1067 .cs-desc {
        font-size: clamp(0.75rem, 1.9vw, 1rem);
        text-align: center;
        line-height: 1.2em;
        font-weight: 700;
        width: 100%;
        max-width: 12ch;
        margin: 0;
        color: var(--bodyTextColorWhite);
        display: block;
      }

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  topper: "Your Topper Text Here"
  mainHeading: "About Our Company"
  mainIntro: "We have been serving for decades, ensuring quality and commitment in all our services."
  secondHeading: "Our Mission"
  secondText: "To provide exceptional services and quality products."
  thirdHeading: "Our Vision"
  thirdText: "To be a leader in the industry by setting high standards and inspiring others."
  firstImgSM: bookshop:generic/image
  firstImgLG: bookshop:generic/image
  firstImgAlt: "Team working together"
  secondImgSM: bookshop:generic/image
  secondImgLG: bookshop:generic/image
  secondImgAlt: "Office environment"
  numberOfYears: "25"
  servingDetails: "Years of Excellence"
  styles:
    color_group: "primary"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  topper:
    comment: "Add a short introductory text."
  mainIntro:
    comment: "Provide a brief introduction in Markdown."
